---
name: Deploy

on:
  push:
    tags:
      - prod

jobs:
  next-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: v16.x
      - name: Generate
        run: |
          yarn install --frozen-lockfile
          yarn run build
          yarn run export
        env:
          BASE_PATH: '/my-personal-website'
          IMAGES_PATH: 'https://clementdv.github.io/my-personal-website/'
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: github-pages
          folder: ./out
